#!/bin/bash
# 
# Alexandre Génin, 2018. MIT License.
# 
TMPDIR="/tmp/tmpfiles_$RANDOM"
mkdir ${TMPDIR}
mkdir "${TMPDIR}/svg"

# We need to trap interruptions to clean up things before quitting
trap interrupt INT

function interrupt() { 
  echo "Got Ctrl+C'd ! Cleaning up and quitting..."
  cleanup
  exit 1
}

function cleanup() {
  # Clean up directories
  echo "Cleaning up..."
  rm -r "$RESDIR" "$TMPDIR"
  mv "$RESDIRTMP" "$RESDIR"
}

function echo_default_info_pmk { 
echo '
#!/usr/bin/presmaker 
# 
# This file contains some information about the presentation in the 
# current directory. It will be sourced by bash, so you can add any variable 
# definition and commands. 

# Basid information about the presentation
author="$USER" 
presdate="$(date +%d\\/%m\\/%Y)"

# Build-related variables
FILESDIR="./slides"
RESDIR="./res"
OUTFILE="$(pwd)/slides.pdf"
RASTERMAXRES="1280"

# presmaker will replace some text fields by the following data: 
# 
# Default tags reminder: 
# Date                    ##DATE##
# Author                  ##AUTHOR##
# Total number of pages   ##TP##
# Current page number     ##CP##
# 
# Please escape special chars which could break the string replacement 
# with sed (e.g. "\"). 
# 
# 
# You can add custom tags using the following arrays: 
CUSTOMTAGS=( "##PTITLE1##" \
            "##PTITLE2##" )
CUSTOMVALS=( "Introduction" \
            "Title of Part 2")
'
}

function echo_default_slide { 
echo \
'<?xml version="1.0" encoding="UTF-8"?>
<svg width="1600" height="1200" version="1.1" viewBox="0 0 423.33332 317.50001" xmlns="http://www.w3.org/2000/svg" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<metadata>
<rdf:RDF>
<cc:Work rdf:about="">
<dc:format>image/svg+xml</dc:format>
<dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>
<dc:title/>
</cc:Work>
</rdf:RDF>
</metadata>
<g transform="translate(0 20.5)">
<rect y="80.787" width="423.33" height="114.93" color="#000000" color-rendering="auto" fill="#24221c" image-rendering="auto" shape-rendering="auto" solid-color="#000000" style="isolation:auto;mix-blend-mode:normal;paint-order:stroke fill markers"/>
<flowRoot color="#000000" color-rendering="auto" fill="#333333" font-family="Sans" font-size="14.667px" image-rendering="auto" letter-spacing="0px" shape-rendering="auto" solid-color="#000000" stroke-linejoin="round" stroke-width="1.5118" text-align="end" text-anchor="end" text-rendering="auto" word-spacing="0px" style="block-progression:tb;filter-blend-mode:normal;filter-gaussianBlur-deviation:0;font-variant-east_asian:normal;isolation:auto;line-height:25px;mix-blend-mode:normal;paint-order:stroke fill markers;text-decoration-color:#000000;text-decoration-line:none;text-decoration-style:solid;text-indent:0;text-transform:none;white-space:normal" xml:space="preserve"><flowRegion><rect x="-420" y="162.86" width="1891.4" height="825.71"/></flowRegion><flowPara/></flowRoot>
<g fill="#ffffff" font-family="Timeless" letter-spacing="0px" shape-rendering="auto" stroke-linejoin="round" text-anchor="end" text-rendering="auto" word-spacing="0px">
<text x="212.25964" y="132.76901" color="#000000" color-rendering="auto" font-size="21.121px" image-rendering="auto" solid-color="#000000" stroke-width="2.1771" text-align="end" style="isolation:auto;line-height:36.00099182px;mix-blend-mode:normal;paint-order:stroke fill markers;text-decoration-color:#000000;text-decoration-line:none;text-decoration-style:solid;text-indent:0;text-transform:none;white-space:normal" xml:space="preserve"><tspan x="212.25964" y="132.76901" fill="#ffffff" font-family="Sans" stroke-width="2.1771" text-align="center" text-anchor="middle">This is my first slide</tspan></text>
<text x="211.66377" y="159.60991" color="#000000" color-rendering="auto" font-size="11.846px" image-rendering="auto" solid-color="#000000" stroke-width="1.221" text-align="end" style="isolation:auto;line-height:20.1914978px;mix-blend-mode:normal;paint-order:stroke fill markers;text-decoration-color:#000000;text-decoration-line:none;text-decoration-style:solid;text-indent:0;text-transform:none;white-space:normal" xml:space="preserve"><tspan x="211.66377" y="159.60991" fill="#ffffff" font-family="Sans" stroke-width="1.221" text-align="center" text-anchor="middle">##AUTHOR## - ##DATE##</tspan></text>
</g>
</g>
</svg>
'
}

# Test if the info.pmk file exists
if [[ -n "$1" ]]; then
  source "$1"
else
  echo "No info file provided. Trying ./info.pmk." 
  
  if [[ -e "./info.pmk" ]]; then 
    source "./info.pmk"
  else 
    "./info.pmk not found, creating default directory structure."
  fi

  if [[ ! -e "./info.pmk" ]]; then
    echo_default_info_pmk > "./info.pmk"
    source "./info.pmk"
    
    echo "Creating resource dir $RESDIR"
    mkdir "$RESDIR"
    
    echo "Creating slides dir $FILESDIR"
    mkdir "$FILESDIR"
    
    echo "Creating default slide"
    echo_default_slide > "./slides/00_00_first_slide.svg"
    
    echo ""
    echo "Setup done, now edit ./$FILESDIR/00_00_first_slide.svg to start working"
    echo "on your slides."
    echo ""
    echo "Create a new slide by adding files in the directory ./$FILESDIR. For"
    echo "example, the files in ./$FILESDIR could look like this: "
    echo "  00_00_first_slide.svg"
    echo "  00_02_some_background.svg"
    echo "  00_04_intro.svg"
    echo "  01_00_results.svg"
    echo "  01_02_more_results.svg"
    echo "  02_99_conclusions.svg"
    echo ""
    echo "Running presmaker again will produce a pdf file with 6 slides, "
    echo "corresponding to each svg file."
    echo "The order of the slides respects the bash sorting order of svg files."
    echo "" 
    echo "You can put images and other files in ./$RESDIR and link them in " 
    echo "inkscape svgs. Raster images will be automatically resized."
    echo "" 
    echo "Some tags can be replaced in the text fields of svg files. See the file"
    echo "info.pmk for more information."
    echo "" 
    echo "Now re-run presmaker to create slides"
    
    exit 0
  fi
fi
RESDIRTMP="${RESDIR}_bak"

# Look for slides in given dir
FILES="$(ls $FILESDIR | egrep '.svg$')"
if [[ $( find ${FILESDIR} -type f | wc -l ) == 0 ]]; then
  echo "No slides found in ${FILESDIR}"
  exit
fi

# Resize images in resources dir 
cp -r "$RESDIR" "$RESDIRTMP"

echo 'Resizing images:'
for i in $(find ${RESDIR} -type f); do
  iext="${i##*.}"
  if [[ $(echo $iext | egrep -Ei 'png|jpg|tif|bmp') ]]; then
    iwidth=$(exiftool -S -ImageWidth ${i} |cut -f2 -d' ')
    iheight=$(exiftool -S -ImageHeight ${i} |cut -f2 -d' ')
    if [[ $iwidth -gt $RASTERMAXRES || $iheight -gt $RASTERMAXRES ]]; then
      echo "  $(basename $i)"
      convert ${i} -resize $RASTERMAXRES "${i}_tmp"
      mv "${i}_tmp" ${i}
    fi
  fi
done

# Process slides
NSLIDES=$(echo "$FILES" | wc -w)
CURSLIDE=1
echo 'Processing slides:'
for i in ${FILES[*]}; do
  echo "  $FILESDIR/$i"
  CURFILE="$FILESDIR""/""$i"
  CURTMP="$TMPDIR/svg/$i"
  TMPOUT="$TMPDIR""/""$(basename $i .svg)"".pdf"
  
  cp "$CURFILE" "$CURTMP"
  
  # Process default tags
  sed -i "s/##DATE##/$presdate/" "$CURTMP" # Date
  sed -i "s/##AUTHOR##/$author/" "$CURTMP" # Author
  sed -i "s/##TP##/"$NSLIDES"/" "$CURTMP"  # Total number of slides
  sed -i "s/##CP##/$CURSLIDE/" "$CURTMP"   # Current slide number
  
  # Process custom tags 
  for tag in $(seq 0 $(( ${#CUSTOMTAGS[@]} - 1 ))); do 
    curtag=${CUSTOMTAGS[$tag]}
    curval=${CUSTOMVALS[$tag]}
    sed -i "s/$curtag/$curval/g" "$CURTMP"
  done
  
  CURSLIDE=$(( $CURSLIDE + 1 )) # Move on to next slide
  
  # Render slide
  inkscape -C -A "$TMPOUT" "$CURTMP";
done

echo "Merging slides"
pdftk $TMPDIR/*.pdf cat output ${OUTFILE}

# Clean up
rm -r "$RESDIR" 
mv "$RESDIRTMP" "$RESDIR"

echo "Created ${OUTFILE}"

exit 0
